bioimageio_core_version: 0.5.3post2
bioimageio_spec_version: 0.4.5post6
error: cannot reshape array of size 491228 into shape (1,3,512,512)
name: reproduce test outputs with ilastik <todo version> (draft) using torchscript
  weights
reason: error
status: failed
traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 127, in test_resource\n    expected = [np.load(str(out_path)) for out_path
    in model.test_outputs]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 127, in <listcomp>\n    expected = [np.load(str(out_path)) for out_path in
    model.test_outputs]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/numpy/lib/npyio.py\",
    line 441, in load\n    pickle_kwargs=pickle_kwargs)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/numpy/lib/format.py\",
    line 787, in read_array\n    array.shape = shape\n"]
